# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
terraform_backend_defaults:
  type: gcs
  configuration:
    bucket: toolkit-dev-staging-tfstate

vars:
  deployment_name: a3u-slurm-preview
  project_id: hpc-toolkit-gsc
  region: europe-west1
  zone: europe-west1-b
  a3u_reservation_name: slurm-gcp-a3u-gsc
  a3u_cluster_size: 2
